# Generated by Django 5.1.6 on 2025-04-23 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDepartmentAdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_notices', models.BooleanField(default=False)),
                ('can_manage_gallery', models.BooleanField(default=False)),
                ('can_manage_syllabus', models.BooleanField(default=False)),
                ('can_manage_results', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subdepartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sub-Department Admin Access',
                'unique_together': {('user', 'sub_department')},
            },
        ),
    ]
