# Generated by Django 5.1.6 on 2025-04-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staffmember_awards_and_recognition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subdepartment'),
        ),
    ]
