# Generated by Django 5.1.6 on 2025-04-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aboutus_sub_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='courses_facilitated',
        ),
    ]
