# Generated by Django 5.1.6 on 2025-04-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_staffmember_courses_facilitated'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='courses_facilitated',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='awards_and_recognition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email_addresses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='mobile_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='professional_activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='qualifications',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='research_co_supervision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='research_publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
