# Generated by Django 5.1.6 on 2025-04-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staffmember_courses_facilitated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='patents',
        ),
    ]
